### PR TITLE
ADM-1312 Payments views

### PR DESCRIPTION
**Pull request by SimonHeathESFA**
Change source of Data_pub.Payments view to use StgPmts.Payment

### CODE REVIEW

**Comment by uhimabindu** [comment]
1) Getting the following error when trying to execute the code.
Msg 245, Level 16, State 1, Line 2
Conversion failed when converting the varchar value 'R10' to data type int.
Warning: Null value is eliminated by an aggregate or other SET operation.

2) Using More CTEs can sometimes have an impact on the Performance, Please check the performance with and without Payments CTE.

3) This Branch is out-of-date with Master, which means it can't be merged. So, Please correct it.

**Comment by uhimabindu** [comment]
1) Payment Age is null for some examples i looked at when it's not null in the existing view
2) ContractType is null -- This was set to null in existing view because we didn't have enough information then but that's not the case now. We have contract type flag for every payment so it needs mapping to the right contract type. This is used by Randeep quite a lot in her reporting.
3) CollectionYear doesnt look right (ex. getting 1819 instead of 2019)
4) TransactionType coming up as unknown for some examples i looked at -- This could be because more transancation types need to be added to reference data but i don't see that in the feature branch.
5) EmployerAccountVersion & ApprenticeshipVersion are set to null - Is this Agreed Logic?

**Comment by Luisa-Rossi** [comment]
@SimonHeathESFA what's the process here? When do you check in all your corrections?

**Comment by Luisa-Rossi** [comment]
nevermind @SimonHeathESFA I found it. Ta

**Comment by uhimabindu** [comment]
The Payment Age is coming up as Null for Collection Period 13 and 14. This was raised earlier too. Please can this be corrected. Thanks.

**Comment by SimonHeathESFA** [comment]
Release candidate for payments view and snapshot changes.

**Pull request merged**
